data:
  tokenizer: null
  train_files: data/wildchat-if_train.parquet
  val_files: data/wildchat-if_val.parquet
  prompt_key: prompt
  max_prompt_length: 1024 # 896 
  max_response_length: 4096
  train_batch_size: 64
  val_batch_size: null
  return_raw_input_ids: False  # This should be set to true when the tokenizer between policy and rm differs
  return_raw_chat: True # Use when the chat template differs between the policy and reward model; IDK what the stuff above is for
  reward_fn_key: data_source
  filter_overlong_prompts: False
  sampler:
    class_path: null
    class_name: null
  shuffle: True
  dataloader_num_workers: 8
  
  # ===== NEW CONFIGS ADDED: Data configuration =====
  use_shm: False
  return_full_prompt: False
  validation_shuffle: False
  filter_overlong_prompts_workers: 1
  truncation: left
  image_key: images
  video_key: videos
  trust_remote_code: False
  return_multi_modal_inputs: True
  custom_cls:
    path: null
    name: null
  datagen:
    path: null
    name: null

# ===== NEW CONFIGS ADDED: Custom reward function =====
custom_reward_function:
  # The path to the file containing your customized reward function.
  # If not specified, pre-implemented reward functions will be used.
  path: null
  # The name of the reward function within the specified file. Default is 'compute_score'.
  name: compute_score

actor_rollout_ref:
  hybrid_engine: True
  # ===== NEW CONFIGS ADDED: NCCL timeout =====
  nccl_timeout: 600
  model:
    path: ${MODEL_PATH}
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: False
    # ===== NEW CONFIGS ADDED: Model configuration =====
    custom_chat_template: null
    exclude_modules: null
    use_liger: false
    use_fused_kernels: null
    fused_kernel_options:
      impl_backend: torch
    trust_remote_code: false
  actor:
    _target_: verl.workers.config.FSDPActorConfig
    strategy: fsdp2
    ppo_mini_batch_size: 64
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 1
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 12500 # n * ${data.max_prompt_length} + ${data.max_response_length}, 32768
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: True # True for GRPO
    kl_loss_coef: 0.001 # for grpo
    kl_loss_type: low_var_kl # for grpo
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1 # sp size
    # ===== NEW CONFIGS ADDED: Actor configuration =====
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    clip_ratio_c: 3.0
    loss_agg_mode: token-mean
    use_torch_compile: true
    policy_loss:
      _target_: verl.workers.config.PolicyLossConfig
      loss_mode: "vanilla"
      clip_cov_ratio: 0.0002
      clip_cov_lb: 1.0
      clip_cov_ub: 5.0
      kl_cov_ratio: 0.0002
      ppo_kl_coef: 0.1
    checkpoint:
      _target_: verl.trainer.config.CheckpointConfig
      save_contents: ['model', 'optimizer', 'extra']
      load_contents: ${.save_contents}
      async_save: False
    optim:
      _target_: verl.workers.config.FSDPOptimizerConfig
      lr: 1e-6
      lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
      warmup_style: constant  # select from constant/cosine
      total_training_steps: -1  # must be override by program
      # ===== NEW CONFIGS ADDED: Optimizer configuration =====
      min_lr_ratio: 0.0
      num_cycles: 0.5
      weight_decay: 0.01
      lr_warmup_steps: -1
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
      # ===== NEW CONFIGS ADDED: FSDP configuration =====
      offload_policy: false
      forward_prefetch: False
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
  ref:
    _target_: verl.workers.config.FSDPRefConfig
    strategy: fsdp2
    # ===== NEW CONFIGS ADDED: Ref configuration =====
    use_torch_compile: true
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      param_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      # ===== NEW CONFIGS ADDED: Ref FSDP configuration =====
      offload_policy: False
      forward_prefetch: False
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_micro_batch_size: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
  rollout:
    name: vllm
    mode: sync
    temperature: 0.7
    val_temperature: 0.7
    top_k: -1 # 0 for hf rollout, -1 for vllm rollout
    top_p: 1
    prompt_length: ${data.max_prompt_length}  # not use for opensource
    response_length: ${data.max_response_length}
    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    gpu_memory_utilization: 0.4 # 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 16384
    max_num_seqs: 64 # 1024
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_micro_batch_size: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    enable_chunked_prefill: True
    # for hf rollout
    do_sample: True
    # number of responses (i.e. num sample times)
    n: 8 # > 1 for grpo
    n_val: 8

    val_kwargs:
      top_k: -1
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False

    max_model_len: null
    engine_kwargs:
      vllm:
        swap_space: null
        disable_mm_preprocessor_cache: False
      sglang:
        attention_backend: null
    
    # ===== NEW CONFIGS ADDED: Rollout configuration =====
    disable_log_stats: True
    multi_stage_wake_up: false
    calculate_log_probs: False
    skip_rollout: False
    skip_dump_dir: /tmp/rollout_dump
    update_weights_bucket_megabytes: 512
    
    # ===== NEW CONFIGS ADDED: Rollout trace configuration =====
    trace:
      backend: null
      token2text: False
    
    # ===== NEW CONFIGS ADDED: Rollout agent configuration =====
    agent:
      num_workers: 8
      agent_loop_config_path: null
      custom_async_server:
        path: null
        name: null
    
    # ===== NEW CONFIGS ADDED: Rollout multi-turn configuration =====
    multi_turn:
      enable: False
      max_assistant_turns: null
      tool_config_path: null
      max_user_turns: null
      max_parallel_calls: 1
      max_tool_response_length: 256
      tool_response_truncate_side: middle
      interaction_config_path: null
      use_inference_chat_template: False
      tokenization_sanity_check_mode: strict
      format: hermes
  
  # ===== NEW CONFIGS ADDED: Profiler configuration =====
  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

critic:
  _target_: verl.workers.config.FSDPCriticConfig
  enable: null
  strategy: fsdp2
  # ===== NEW CONFIGS ADDED: Critic configuration =====
  rollout_n: ${oc.select:actor_rollout_ref.rollout.n,1}
  optim:
    _target_: verl.workers.config.FSDPOptimizerConfig
    lr: 5e-6
    lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
    warmup_style: constant  # select from constant/cosine
    total_training_steps: -1  # must be override by program
    # ===== NEW CONFIGS ADDED: Critic optimizer configuration =====
    min_lr_ratio: null
    weight_decay: 0.01
    lr_warmup_steps: -1
  model:
    _target_: verl.workers.config.FSDPCriticModelCfg
    path: ${actor_rollout_ref.model.path}
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    # ===== NEW CONFIGS ADDED: Critic model configuration =====
    use_shm: False
    enable_activation_offload: False
    lora_rank: 0
    lora_alpha: 16
    target_modules: all-linear
    trust_remote_code: ${oc.select:actor_rollout_ref.model.trust_remote_code,false}
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      param_offload: False
      optimizer_offload: False
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
      # ===== NEW CONFIGS ADDED: Critic FSDP configuration =====
      offload_policy: False
      forward_prefetch: False
  ppo_mini_batch_size: 64
  ppo_micro_batch_size: 8
  forward_micro_batch_size: 4 # 8, 4
  use_dynamic_bsz: False
  ppo_max_token_len_per_gpu: 12000 # 32768
  forward_max_token_len_per_gpu: 12000 # 32768
  ulysses_sequence_parallel_size: 1 # sp size
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5
  # ===== NEW CONFIGS ADDED: Critic additional configuration =====
  loss_agg_mode: ${oc.select:actor_rollout_ref.actor.loss_agg_mode,token-mean}
  checkpoint:
    _target_: verl.trainer.config.CheckpointConfig
    save_contents: ['model', 'optimizer', 'extra']
    load_contents: ${.save_contents}
    async_save: False
  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

reward_model:
  enable: True
  strategy: fsdp2
  model:
    model_type: seqcls
    use_shm: False
    input_tokenizer: ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: models/Skywork-Reward-Llama-3.1-8B-v0.2
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False # Since its a seqcls model
    # ===== NEW CONFIGS ADDED: Reward model configuration =====
    use_fused_kernels: ${actor_rollout_ref.model.use_fused_kernels}
    trust_remote_code: False
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      wrap_policy:
        min_num_params: 0
      param_offload: False
      fsdp_size: -1
      reshard_after_forward: True
      forward_prefetch: False
      # ===== NEW CONFIGS ADDED: Reward model FSDP configuration =====
      offload_policy: False
  micro_batch_size_per_gpu: 1
  micro_batch_size: null
  max_length: null
  ulysses_sequence_parallel_size: 1 # sp size
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  longcot_config: ${actor_rollout_ref.model.path}/longcot_config.json
  strict: False
  # ===== NEW CONFIGS ADDED: Reward model additional configuration =====
  reward_manager: naive
  launch_reward_fn_async: False
  sandbox_fusion:
    url: null
    max_concurrent: 64
    memory_limit_mb: 1024
  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

algorithm:
  _target_: verl.trainer.config.AlgoConfig
  gamma: 1.0
  lam: 1.0
  use_kl_in_reward: False # not in reward, only in algo
  adv_estimator: grpo 
  kl_penalty: kl  # how to estimate kl divergence
  norm_adv_by_std_in_grpo: True
  kl_ctrl:
    _target_: verl.trainer.config.KLControlConfig
    type: fixed
    kl_coef: 0.001
    # ===== NEW CONFIGS ADDED: KL control configuration =====
    horizon: 10000
    target_kl: 0.1
  
  # ===== NEW CONFIGS ADDED: Preference feedback PPO configuration =====
  use_pf_ppo: False
  pf_ppo:
    reweight_method: pow
    weight_pow: 2.0

trainer:
  rejection_sample: False # Reject sample prompts that all succeed or all fail (0 signal for GRPO due to normalization).
  rejection_sample_multiplier: 2 # Multiple the training batch size by this factor to account for rejection sampling reduction.
  total_epochs: 2
  total_training_steps: null
  project_name: verl
  experiment_name: grpo__llamabase__warm-start__think
  logger: ['wandb'] # 'console', 'wandb'
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: 45
  test_freq: 45
  critic_warmup: 0
  default_hdfs_dir: null 
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  val_before_train: False
  device: cuda
  
  # ===== NEW CONFIGS ADDED: Trainer configuration =====
  balance_batch: True
  profile_steps: null
  profile_continuous_steps: False
  log_val_generations: 0
  rollout_data_dir: rollouts/llama-longcot
  validation_data_dir: null
  esi_redundant_time: 0
  resume_mode: auto
  resume_from_path: null
  val_only: False
  del_local_ckpt_after_load: False
  max_actor_ckpt_to_keep: null
  max_critic_ckpt_to_keep: null
  ray_wait_register_center_timeout: 300
  use_legacy_worker_impl: auto
  
  # ===== NEW CONFIGS ADDED: Controller Nsight Systems Options =====
  controller_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"
  
  # ===== NEW CONFIGS ADDED: Worker Nsight Systems Options =====
  worker_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"
    capture-range: "cudaProfilerApi"
    capture-range-end: null
    kill: none

  npu_profile:
    options:
      save_path: ./profiler_data
      roles: ["all"]
      level: level1
      with_memory: False
      record_shapes: False
      with_npu: True
      with_cpu: True

# ===== NEW CONFIGS ADDED: Ray initialization configuration =====
ray_init:
  num_cpus: null
  timeline_json_file: null