data:
  tokenizer: null
  train_files: data/wildchat-if_train.parquet
  val_files: data/wildchat-if_val.parquet
  prompt_key: prompt
  max_prompt_length: 1024
  max_response_length: 4096
  train_batch_size: 64 
  val_batch_size: null
  return_raw_input_ids: False
  return_raw_chat: True
  reward_fn_key: data_source
  filter_overlong_prompts: False
  sampler:
    class_path: null
    class_name: null
  shuffle: True
  dataloader_num_workers: 8

  use_shm: False
  return_full_prompt: False
  validation_shuffle: False
  filter_overlong_prompts_workers: 1
  truncation: left
  image_key: images
  video_key: videos
  trust_remote_code: False
  return_multi_modal_inputs: True
  custom_cls:
    path: null
    name: null
  datagen:
    path: null
    name: null

custom_reward_function:
  path: null
  name: compute_score

actor_rollout_ref:
  hybrid_engine: True
  nccl_timeout: 600
  model:
    path: ${MODEL_PATH}
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: False
    custom_chat_template: null
    exclude_modules: null
    use_liger: false
    use_fused_kernels: null
    fused_kernel_options:
      impl_backend: torch
    trust_remote_code: false
  actor:
    _target_: verl.workers.config.FSDPActorConfig
    strategy: fsdp2
    ppo_mini_batch_size: 64
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 1
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 12500
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    clip_ratio_c: 3.0
    loss_agg_mode: token-mean
    use_torch_compile: true
    policy_loss:
      _target_: verl.workers.config.PolicyLossConfig
      loss_mode: "vanilla"
      clip_cov_ratio: 0.0002
      clip_cov_lb: 1.0
      clip_cov_ub: 5.0
      kl_cov_ratio: 0.0002
      ppo_kl_coef: 0.1
    checkpoint:
      _target_: verl.trainer.config.CheckpointConfig
      save_contents: ['model', 'optimizer', 'extra']
      load_contents: ${.save_contents}
      async_save: False
    optim:
      _target_: verl.workers.config.FSDPOptimizerConfig
      lr: 1e-6
      lr_warmup_steps_ratio: 0.
      warmup_style: constant
      total_training_steps: -1
      min_lr_ratio: 0.0
      num_cycles: 0.5
      weight_decay: 0.01
      lr_warmup_steps: -1
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      wrap_policy:
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
      offload_policy: false
      forward_prefetch: False
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
  ref:
    _target_: verl.workers.config.FSDPRefConfig
    strategy: fsdp2
    use_torch_compile: true
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      param_offload: False
      wrap_policy:
        min_num_params: 0
      offload_policy: False
      forward_prefetch: False
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_micro_batch_size: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size}
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
  rollout:
    name: vllm
    mode: sync
    temperature: 0.7
    val_temperature: 0.7
    top_k: -1
    top_p: 1
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    dtype: bfloat16
    gpu_memory_utilization: 0.4
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 16384
    max_num_seqs: 64
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_micro_batch_size: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    enable_chunked_prefill: True
    do_sample: True
    n: 8
    n_val: 8

    val_kwargs:
      top_k: -1
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False

    max_model_len: null
    engine_kwargs:
      vllm:
        swap_space: null
        disable_mm_preprocessor_cache: False
      sglang:
        attention_backend: null

    disable_log_stats: True
    multi_stage_wake_up: false
    calculate_log_probs: False
    skip_rollout: False
    skip_dump_dir: /tmp/rollout_dump
    update_weights_bucket_megabytes: 512

    trace:
      backend: null
      token2text: False

    agent:
      num_workers: 8
      agent_loop_config_path: null
      custom_async_server:
        path: null
        name: null

    multi_turn:
      enable: False
      max_assistant_turns: null
      tool_config_path: null
      max_user_turns: null
      max_parallel_calls: 1
      max_tool_response_length: 256
      tool_response_truncate_side: middle
      interaction_config_path: null
      use_inference_chat_template: False
      tokenization_sanity_check_mode: strict
      format: hermes

  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

critic:
  _target_: verl.workers.config.FSDPCriticConfig
  enable: null
  strategy: fsdp2
  rollout_n: ${oc.select:actor_rollout_ref.rollout.n,1}
  optim:
    _target_: verl.workers.config.FSDPOptimizerConfig
    lr: 1e-5 
    lr_warmup_steps_ratio: 0.
    warmup_style: constant
    total_training_steps: -1
    min_lr_ratio: null
    weight_decay: 0.01
    lr_warmup_steps: -1
  model:
    _target_: verl.workers.config.FSDPCriticModelCfg
    path: ${actor_rollout_ref.model.path}
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    use_shm: False
    enable_activation_offload: False
    lora_rank: 0
    lora_alpha: 16
    target_modules: all-linear
    trust_remote_code: ${oc.select:actor_rollout_ref.model.trust_remote_code,false}
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      param_offload: False
      optimizer_offload: False
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
      offload_policy: False
      forward_prefetch: False
  ppo_mini_batch_size: 64
  ppo_micro_batch_size: 8
  forward_micro_batch_size: 4
  use_dynamic_bsz: False
  ppo_max_token_len_per_gpu: 12000
  forward_max_token_len_per_gpu: 12000
  ulysses_sequence_parallel_size: 1
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5
  loss_agg_mode: ${oc.select:actor_rollout_ref.actor.loss_agg_mode,token-mean}
  checkpoint:
    _target_: verl.trainer.config.CheckpointConfig
    save_contents: ['model', 'optimizer', 'extra']
    load_contents: ${.save_contents}
    async_save: False
  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

reward_model:
  enable: True
  strategy: fsdp2
  model:
    model_type: seqcls
    use_shm: False
    input_tokenizer: ${actor_rollout_ref.model.path}
    path: models/Skywork-Reward-Llama-3.1-8B-v0.2
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False
    use_fused_kernels: ${actor_rollout_ref.model.use_fused_kernels}
    trust_remote_code: False
    fsdp_config:
      _target_: verl.workers.config.FSDPEngineConfig
      wrap_policy:
        min_num_params: 0
      param_offload: False
      fsdp_size: -1
      reshard_after_forward: True
      forward_prefetch: False
      offload_policy: False
  micro_batch_size_per_gpu: 1
  micro_batch_size: null
  max_length: null
  ulysses_sequence_parallel_size: 1
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  longcot_config: null
  strict: False
  reward_manager: naive
  launch_reward_fn_async: False
  sandbox_fusion:
    url: null
    max_concurrent: 64
    memory_limit_mb: 1024
  profiler:
    _target_: verl.utils.profiler.ProfilerConfig
    discrete: False
    all_ranks: False
    ranks: []

algorithm:
  _target_: verl.trainer.config.AlgoConfig
  gamma: 1.0
  lam: 1.0
  use_kl_in_reward: False
  adv_estimator: grpo 
  kl_penalty: kl
  norm_adv_by_std_in_grpo: True
  kl_ctrl:
    _target_: verl.trainer.config.KLControlConfig
    type: fixed
    kl_coef: 0.001
    horizon: 10000
    target_kl: 0.1

  use_pf_ppo: False
  pf_ppo:
    reweight_method: pow
    weight_pow: 2.0

trainer:
  rejection_sample: False
  rejection_sample_multiplier: 2
  total_epochs: 2
  total_training_steps: null
  project_name: verl
  experiment_name: grpo__llamabase__warm-start__nothink
  logger: ['wandb']
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: 45
  test_freq: 45
  critic_warmup: 0
  default_hdfs_dir: null 
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  val_before_train: False
  device: cuda

  balance_batch: True
  profile_steps: null
  profile_continuous_steps: False
  log_val_generations: 0
  rollout_data_dir: null
  validation_data_dir: null
  esi_redundant_time: 0
  resume_mode: auto
  resume_from_path: null
  val_only: False
  del_local_ckpt_after_load: False
  max_actor_ckpt_to_keep: null
  max_critic_ckpt_to_keep: null
  ray_wait_register_center_timeout: 300
  use_legacy_worker_impl: auto

  controller_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"

  worker_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"
    capture-range: "cudaProfilerApi"
    capture-range-end: null
    kill: none

  npu_profile:
    options:
      save_path: ./profiler_data
      roles: ["all"]
      level: level1
      with_memory: False
      record_shapes: False
      with_npu: True
      with_cpu: True

ray_init:
  num_cpus: null
  timeline_json_file: null
